package uk.gov.hmcts.reform.sscspostdeploymentfttests.util;

public enum LoggerMessage {
    SCENARIO_START,
    SCENARIO_DISABLED,
    SCENARIO_ENABLED,
    SCENARIO_FINISHED,
    SCENARIO_SUCCESSFUL,
    SCENARIO_BEFORE_FOUND,
    SCENARIO_BEFORE_COMPLETED,
    SCENARIO_ROLE_ASSIGNMENT_FOUND,
    SCENARIO_ROLE_ASSIGNMENT_COMPLETED,
    SCENARIO_UPDATE_CASE_FOUND,
    SCENARIO_UPDATE_CASE_COMPLETED,
    CLEANUP_USERS_RUNNING,
    CLEANUP_USERS_FINISHED,
    SCENARIO_RUNNING,
    SCENARIO_RUNNING_TIME,
    SCENARIO_FAILED
}
